#!/usr/bin/env python3
"""Turn the CI matrix's per-version results into a compatibility table.

CI already runs every demo against several Godot versions. That result currently
evaporates when the job ends. This keeps it: which demos pass on which engine,
published so a visitor can answer "what version do I need for this one" without
trying it.

    ./run-tests.sh | tee results-4.7.1.txt      # one per version, in CI
    tools/build_compat.py results/              # -> docs/COMPATIBILITY.md
    tools/build_compat.py results/ --check      # fail if it is out of date

It also writes a one-line badge into the root README, between its
`<!-- compat-badge -->` markers, so the front page cannot claim a state the
table disagrees with.

Accepts either a directory of `results-<version>.txt` files or a directory of
per-version subdirectories, which is how actions/download-artifact lays them out.
"""

import glob
import os
import re
import sys

OUT = "docs/COMPATIBILITY.md"

# The badge lives between these in the root README, so it can be regenerated
# without touching the prose around it.
BADGE_START = "<!-- compat-badge -->"
BADGE_END = "<!-- /compat-badge -->"
RESULT_LINE = re.compile(r"^(PASS|FAIL|SKIP)\s+(\S+)")
VERSION_FROM_NAME = re.compile(r"results-([0-9]+(?:\.[0-9]+)*)")


def find_result_files(root):
    """Every results-<version>.txt under root, at any depth."""
    found = []
    for path in glob.glob(os.path.join(root, "**", "results-*.txt"), recursive=True):
        match = VERSION_FROM_NAME.search(os.path.basename(path))
        if match:
            found.append((match.group(1), path))
    return sorted(found)


def parse(path):
    """demo -> PASS/FAIL/SKIP"""
    status = {}
    with open(path, encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = RESULT_LINE.match(line)
            if match:
                status[match.group(2)] = match.group(1)
    return status


def badge(versions, results, demos):
    """A one-line status for the top of the README.

    Written as plain text rather than an image: it renders the same in a
    terminal, in an editor preview and on a network the reader may not have,
    and it cannot go stale independently of the table it is generated with.
    """
    newest = versions[-1]
    passing = sum(1 for s in results[newest].values() if s == "PASS")
    total = len(demos)
    mark = "passing" if passing == total else "%d failing" % (total - passing)
    return ("%s\n**Godot %s** — %d/%d demos %s. "
            "[Full table](docs/COMPATIBILITY.md)\n%s"
            % (BADGE_START, newest, passing, total, mark, BADGE_END))


def write_badge(text, check):
    """Put the badge in the README, between its markers."""
    readme = "README.md"
    with open(readme, encoding="utf-8") as handle:
        current = handle.read()
    if BADGE_START not in current:
        return ["README.md has no %s marker to put the badge in" % BADGE_START]
    start = current.index(BADGE_START)
    end = current.index(BADGE_END) + len(BADGE_END)
    updated = current[:start] + text + current[end:]
    if updated == current:
        return []
    if check:
        return ["README.md badge is out of date — run tools/build_compat.py"]
    with open(readme, "w", encoding="utf-8") as handle:
        handle.write(updated)
    return []


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    check = "--check" in sys.argv
    root = args[0] if args else "results"
    files = find_result_files(root)
    if not files:
        print("no results-<version>.txt files found under %r" % root, file=sys.stderr)
        return 2

    versions = [v for v, _ in files]
    results = {v: parse(p) for v, p in files}
    demos = sorted({d for status in results.values() for d in status})

    # A demo only worth calling out is one that differs across versions; listing
    # 165 rows of all-green would bury the useful information.
    differing = [d for d in demos
                 if len({results[v].get(d, "—") for v in versions}) > 1]

    lines = ["# Compatibility", "",
             "Which demos pass on which Godot version, taken from the CI matrix.",
             "Generated by `tools/build_index.py`'s sibling `tools/build_compat.py` —",
             "it reports what actually ran, not what anyone believes.", "",
             "Versions tested: " + ", ".join("`%s`" % v for v in versions), ""]

    if differing:
        lines += ["## Demos that differ between versions", "",
                  "These are the ones worth knowing about before you copy them.", "",
                  "| Demo | " + " | ".join(versions) + " |",
                  "|------|" + "|".join(["---"] * len(versions)) + "|"]
        for demo in differing:
            marks = []
            for v in versions:
                status = results[v].get(demo, "—")
                marks.append({"PASS": "✅", "FAIL": "❌", "SKIP": "⚪"}.get(status, "—"))
            lines.append("| [%s](../%s) | %s |" % (demo, demo, " | ".join(marks)))
        lines.append("")
    else:
        lines += ["## Every demo behaves identically on every tested version", "",
                  "Nothing differs across `%s`." % "`, `".join(versions), ""]

    lines += ["## Summary", "", "| Version | Passing | Failing |",
              "|---------|---------|---------|"]
    for v in versions:
        status = results[v]
        passing = sum(1 for s in status.values() if s == "PASS")
        failing = sum(1 for s in status.values() if s == "FAIL")
        lines.append("| `%s` | %d | %d |" % (v, passing, failing))

    lines += ["", "---", "", "_%d demos across %d versions._" % (len(demos), len(versions))]

    content = "\n".join(lines) + "\n"
    problems = write_badge(badge(versions, results, demos), check)

    if check:
        existing = ""
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as handle:
                existing = handle.read()
        if existing != content:
            problems.append("%s is out of date — run tools/build_compat.py" % OUT)
        if problems:
            for problem in problems:
                print("  " + problem)
            return 1
        print("compatibility table and badge are up to date")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(content)
    if problems:
        for problem in problems:
            print("  " + problem)
        return 1
    print("wrote %s — %d demos, %d differ across versions" % (OUT, len(demos), len(differing)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
