#!/usr/bin/env python3
"""Turn the CI matrix's per-version results into a compatibility table.

CI already runs every demo against several Godot versions. That result currently
evaporates when the job ends. This keeps it: which demos pass on which engine,
published so a visitor can answer "what version do I need for this one" without
trying it.

    ./run-tests.sh | tee results-4.7.1.txt      # one per version, in CI
    tools/build_compat.py results/              # -> docs/COMPATIBILITY.md

Accepts either a directory of `results-<version>.txt` files or a directory of
per-version subdirectories, which is how actions/download-artifact lays them out.
"""

import glob
import os
import re
import sys

OUT = "docs/COMPATIBILITY.md"
RESULT_LINE = re.compile(r"^(PASS|FAIL|SKIP)\s+(\S+)")
VERSION_FROM_NAME = re.compile(r"results-([0-9]+(?:\.[0-9]+)*)")


def find_result_files(root):
    """Every results-<version>.txt under root, at any depth."""
    found = []
    for path in glob.glob(os.path.join(root, "**", "results-*.txt"), recursive=True):
        match = VERSION_FROM_NAME.search(os.path.basename(path))
        if match:
            found.append((match.group(1), path))
    return sorted(found)


def parse(path):
    """demo -> PASS/FAIL/SKIP"""
    status = {}
    with open(path, encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = RESULT_LINE.match(line)
            if match:
                status[match.group(2)] = match.group(1)
    return status


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "results"
    files = find_result_files(root)
    if not files:
        print("no results-<version>.txt files found under %r" % root, file=sys.stderr)
        return 2

    versions = [v for v, _ in files]
    results = {v: parse(p) for v, p in files}
    demos = sorted({d for status in results.values() for d in status})

    # A demo only worth calling out is one that differs across versions; listing
    # 165 rows of all-green would bury the useful information.
    differing = [d for d in demos
                 if len({results[v].get(d, "—") for v in versions}) > 1]

    lines = ["# Compatibility", "",
             "Which demos pass on which Godot version, taken from the CI matrix.",
             "Generated by `tools/build_index.py`'s sibling `tools/build_compat.py` —",
             "it reports what actually ran, not what anyone believes.", "",
             "Versions tested: " + ", ".join("`%s`" % v for v in versions), ""]

    if differing:
        lines += ["## Demos that differ between versions", "",
                  "These are the ones worth knowing about before you copy them.", "",
                  "| Demo | " + " | ".join(versions) + " |",
                  "|------|" + "|".join(["---"] * len(versions)) + "|"]
        for demo in differing:
            marks = []
            for v in versions:
                status = results[v].get(demo, "—")
                marks.append({"PASS": "✅", "FAIL": "❌", "SKIP": "⚪"}.get(status, "—"))
            lines.append("| [%s](../%s) | %s |" % (demo, demo, " | ".join(marks)))
        lines.append("")
    else:
        lines += ["## Every demo behaves identically on every tested version", "",
                  "Nothing differs across `%s`." % "`, `".join(versions), ""]

    lines += ["## Summary", "", "| Version | Passing | Failing |",
              "|---------|---------|---------|"]
    for v in versions:
        status = results[v]
        passing = sum(1 for s in status.values() if s == "PASS")
        failing = sum(1 for s in status.values() if s == "FAIL")
        lines.append("| `%s` | %d | %d |" % (v, passing, failing))

    lines += ["", "---", "", "_%d demos across %d versions._" % (len(demos), len(versions))]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote %s — %d demos, %d differ across versions" % (OUT, len(demos), len(differing)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
